JOB_APP:
  first_name: "Foo"
  last_name: "Bar"
  email: "pkarimulla9@gmail.com"
  phone: "123-456-7890"
  resume: "resume/resume.pdf"  # Relative path
  linkedin: "https://www.linkedin.com/in/foobar"
  location: "San Francisco, CA, USA"
  school: "MIT"
  degree: "Bachelor's"
  work_auth: "Authorized to work for any employer"
